"""Add drink table

Revision ID: 55d536ba9018
Revises: c03c8e9f7e35
Create Date: 2021-06-27 17:38:51.963995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d536ba9018'
down_revision = 'c03c8e9f7e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drink_id'), 'drink', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drink_id'), table_name='drink')
    op.drop_table('drink')
    # ### end Alembic commands ###
